context:
  name: dataframely
  version: "3.1.1"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: dfe4d89e3f835545c820e5540b84693bb19ad6728178bc1bd007490e78b29d5a

build:
  number: 0
  skip: not (match(python, python_min ~ ".*") and is_abi3)
  python:
    version_independent: true

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - crossenv
        - maturin >=1.7,<2
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - cargo-auditable
  host:
    - python
    - python-abi3
    - pip
    - maturin >=1.7,<2
  run:
    - python
    - numpy
    - polars >=1.35
    - typing_extensions
  run_constraints:
    - pydantic >=2
    - sqlalchemy >=2

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - "*"
      imports:
        - dataframely
      pip_check: true
  - requirements:
      run:
        - abi3audit
    script:
      - if: unix
        then: abi3audit $SP_DIR/dataframely/_native.abi3.so -s -v --assume-minimum-abi3 ${{ python_min }}
        else: abi3audit %SP_DIR%/dataframely/_native.pyd -s -v --assume-minimum-abi3 ${{ python_min }}

about:
  homepage: https://github.com/Quantco/dataframely
  summary: A declarative, polars-native data frame validation library.
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  documentation: https://dataframely.readthedocs.io/
  repository: https://github.com/Quantco/dataframely

extra:
  recipe-maintainers:
    - borchero
    - delsner
    - AndreasAlbertQC
